language: java
jdk:
  - oraclejdk8

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - psql -c 'create database helloBackEnd;' -U postgres
  - psql -c "CREATE USER aleksandrbogomolov WITH PASSWORD 'password';" -U postgres
  - cp database.yml.travis config/database.yml
