language: java
jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'create database helloBackEnd;' -U postgres
  - psql -c "CREATE USER aleksandrbogomolov WITH PASSWORD 'password';" -U postgres

postgres:
  - adapter: postgresql
  - database: helloBackEnd
  - username: aleksandrbogomolov
  - password: password
